export const acuteCodes = {
    'J441': 'Chronic obstructive pulmonary disease with (acute) exacerbation',
    'J189': 'Pneumonia, unspecified organism',
    'J181': 'Lobar pneumonia, unspecified organism',
    'J13': 'Pneumonia due to Streptococcus pneumoniae',
    'V*': 'Prohibited V-Y Codes',
    'W*': 'Prohibited V-Y Codes',
    'X*': 'Prohibited V-Y Codes',
    'Y*': 'Prohibited V-Y Codes',
    'Z1*': 'Prohibited Z Codes',
    'Z2*': 'Prohibited Z Codes',
    'Z3*': 'Prohibited Z Codes',
    'Z5*': 'Prohibited Z Codes',
    'Z6*': 'Prohibited Z Codes',
    'Z71*': 'Prohibited Z Codes',
    'Z72*': 'Prohibited Z Codes',
    'Z73*': 'Prohibited Z Codes',
    'Z75*': 'Prohibited Z Codes',
    'Z76*': 'Prohibited Z Codes',
    'Z79*': 'Prohibited Z Codes',
    'Z80*': 'Prohibited Z Codes',
    'Z81*': 'Prohibited Z Codes',
    'Z82*': 'Prohibited Z Codes',
    'Z83*': 'Prohibited Z Codes',
    'Z84*': 'Prohibited Z Codes',
    'Z85*': 'Prohibited Z Codes',
    'Z87*': 'Prohibited Z Codes',
    'Z88*': 'Prohibited Z Codes',
    'Z92*': 'Prohibited Z Codes',
    'Z94*': 'Prohibited Z Codes',
    'Z95*': 'Prohibited Z Codes',
    'Z97*': 'Prohibited Z Codes',
    'Z98*': 'Prohibited Z Codes',
    'Z960': 'Prohibited Z Codes',
    'Z961': 'Prohibited Z Codes',
    'Z964*': 'Prohibited Z Codes',
    'Z965': 'Prohibited Z Codes',
    'Z9689': 'Prohibited Z Codes',
    'Z969': 'Prohibited Z Codes',
    'Z911*': 'Prohibited Z Codes',
    'Z914*': 'Prohibited Z Codes',
    'Z9182': 'Prohibited Z Codes',
    'Z9183': 'Prohibited Z Codes',
    'Z9184*': 'Prohibited Z Codes',
    'Z9189': 'Prohibited Z Codes',
    'J01*': 'Acute sinusitis',
    'J02*': 'Acute pharyngitis',
    'J03*': 'Acute tonsillitis',
    'J04*': 'Acute tracheitis',
    'J05*': 'Acute obstructive laryngitis [croup] and epiglottitis',
    'J06*': 'Acute upper respiratory infections of multiple and unspecified sites',
    'G4733': 'OSA',
    'R0683': 'Snoring'
};

export const chronicCodes = {
    c3480: 'Malignant neoplasm of overlapping sites of unspecified bronchus and lung',
    C3491: 'Malignant neoplasm of unspecified part of right bronchus or lung',
    C3492: 'Malignant neoplasm of unspecified part of left bronchus or lung',
    C7800: 'Secondary malignant neoplasm of unspecified lung',
    C7801: 'Secondary malignant neoplasm of right lung',
    C7802: 'Secondary malignant neoplasm of left lung',
    E840: 'Cystic fibrosis with pulmonary manifestations',
    E848: 'Cystic fibrosis with other manifestations',
    E849: 'Cystic fibrosis, unspecified',
    I214: 'Non-ST elevation (NSTEMI) myocardial infarction',
    I270: 'Primary pulmonary hypertension',
    I272: 'Other secondary pulmonary hypertension',
    I2720: 'Pulmonary hypertension, unspecified',
    I2723: 'Pulmonary hypertension due to lung diseases and hypoxia',
    I5020: 'Unspecified systolic (congestive) heart failure',
    I5022: 'Chronic systolic (congestive) heart failure',
    I5030: 'Unspecified diastolic (congestive) heart failure',
    I5032: 'Chronic diastolic (congestive) heart failure',
    I5040: 'Unspecified combined systolic (congestive) and diastolic (congestive) heart failure',
    I5042: 'Chronic combined systolic (congestive) and diastolic (congestive) heart failure',
    I509: 'Heart failure, unspecified',
    I739: 'Peripheral vascular disease, unspecified',
    J410: 'Simple chronic bronchitis',
    J42: 'Unspecified chronic bronchitis',
    J430: 'Unilateral pulmonary emphysema [MacLeod\'s syndrome]',
    J431: 'Panlobular emphysema',
    J432: 'Centrilobular emphysema',
    J438: 'Other emphysema',
    J439: 'Emphysema, unspecified',
    J449: 'Chronic obstructive pulmonary disease, unspecified',
    J4540: 'Moderate persistent asthma, uncomplicated',
    J45909: 'Unspecified asthma, uncomplicated',
    J45998: 'Other asthma',
    J479: 'Bronchiectasis, uncomplicated',
    J811: 'Chronic pulmonary edema',
    J8410: 'Pulmonary fibrosis, unspecified',
    J84112: 'Idiopathic pulmonary fibrosis',
    J849: 'Interstitial pulmonary disease, unspecified',
    J910: 'Malignant pleural effusion',
    I110: 'Hypertensive heart disease with heart failure',
    I2510: 'Atherosclerotic heart disease of native coronary artery without angina pectoris',
    I429: 'Cardiomyopathy, unspecified',
    I480: 'Paroxysmal atrial fibrillation',
    I482: 'Chronic atrial fibrillation',
    J918: 'Pleural effusion in other conditions classified elsewhere',
    J9610: 'Chronic respiratory failure, unspecified whether with hypoxia or hypercapnia',
    J9611: 'Chronic respiratory failure with hypoxia',
    J9612: 'Chronic respiratory failure with hypercapnia',
    J9690: 'Respiratory failure, unspecified whether with hypoxia or hypercapnia',
    J9691: 'Respiratory failure, unspecified',
    J9692: 'Respiratory failure, unspecified with hypoxia',
    J9811: 'Respiratory failure, unspecified with hypercapnia'
};